const data = [
  {
    id: 0,
    imgLink: "",
    postLink: "",
    title: "Technology",
    authorName: "Suresh Yadav",
    date: "March 30 2023",
    readTime: "6 min read",
    description: "Hello Bro",
    category: ["Technology", "AI"],
  },
  {
    id: 1,
    imgLink: "",
    postLink: "",
    title: "Environment",
    authorName: "Suresh Yadav",
    date: "March 30 2023",
    readTime: "6 min read",
    description: "Environment is best",
    category: ["Environment", "Nature"],
  },
  {
    id: 2,
    imgLink: "",
    postLink: "",
    title: "Education",
    authorName: "Suresh Yadav",
    date: "March 30 2023",
    readTime: "6 min read",
    description: "Education is best for life.",
    category: ["Education", "Study"],
  },
  {
    id: 3,
    imgLink: "",
    postLink: "",
    title: "Learn AI",
    authorName: "Suresh Yadav",
    date: "March 30 2023",
    readTime: "6 min read",
    description: "Education is best for life.",
    category: ["Education", "Study"],
  },
];
